use crate::AppState;
use rusqlite::params;
use serde::Serialize;
use std::collections::HashSet;
use tauri::State;
use tauri_plugin_shell::ShellExt;
use crate::commands::scripts::RunResult;
use crate::commands::exec::ps_bin;

#[derive(Serialize)]
pub struct BuilderDefs {
    pub categories: Vec<serde_json::Value>,
    pub presets: serde_json::Value,
}

/// Walk up from exe dir to find data/builder (handles dev: target/debug/ctrl.exe → project root)
fn find_builder_dir() -> std::path::PathBuf {
    let exe_dir = std::env::current_exe().ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    let mut dir = exe_dir.clone();
    for _ in 0..6 {
        let candidate = dir.join("data").join("builder");
        if candidate.exists() { return candidate; }
        if !dir.pop() { break; }
    }
    exe_dir.join("data").join("builder")
}

fn load_categories() -> Vec<serde_json::Value> {
    let data_dir = find_builder_dir();
    let mut cats = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&data_dir) {
        let mut files: Vec<_> = entries.filter_map(|e| e.ok())
            .filter(|e| {
                let name = e.file_name();
                let s = name.to_string_lossy();
                s.ends_with(".json") && !s.starts_with('_')
            })
            .collect();
        files.sort_by_key(|e| e.file_name());
        for entry in files {
            if let Ok(content) = std::fs::read_to_string(entry.path()) {
                if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
                    cats.push(val);
                }
            }
        }
    }
    cats
}

fn load_presets() -> serde_json::Value {
    let meta_path = find_builder_dir().join("_meta.json");
    if let Ok(content) = std::fs::read_to_string(meta_path) {
        if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
            if let Some(p) = val.get("presets") { return p.clone(); }
        }
    }
    serde_json::Value::Object(Default::default())
}

/// Recursively collect PS1 strings for selected IDs, in JSON order.
fn collect_scripts(val: &serde_json::Value, ids: &HashSet<String>, out: &mut Vec<String>) {
    match val {
        serde_json::Value::Array(arr) => {
            for item in arr { collect_scripts(item, ids, out); }
        }
        serde_json::Value::Object(obj) => {
            if let Some(id) = obj.get("id").and_then(|v| v.as_str()) {
                if ids.contains(id) {
                    if let Some(serde_json::Value::String(s)) = obj.get("ps1") {
                        if !s.is_empty() { out.push(s.clone()); }
                    }
                }
            }
            if let Some(items) = obj.get("items") {
                collect_scripts(items, ids, out);
            }
        }
        _ => {}
    }
}

const SCRIPT_HEADER: &str = r#"# Script generated by >_CTRL
# Check if the script is running as admin
$ProgressPreference = "SilentlyContinue"
$ErrorActionPreference = "SilentlyContinue"
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

"#;

const SCRIPT_FOOTER: &str = r#"
# ── Finalise ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Restarting Explorer..." -ForegroundColor Cyan
Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500
Start-Process explorer
Write-Host "Done." -ForegroundColor Green
Read-Host "Press Enter to exit"
"#;

#[tauri::command]
pub fn get_builder_actions(_app: tauri::AppHandle) -> Result<BuilderDefs, String> {
    Ok(BuilderDefs { categories: load_categories(), presets: load_presets() })
}

#[tauri::command]
pub fn build_script(_app: tauri::AppHandle, action_ids: Vec<String>, output_type: String) -> Result<String, String> {
    let _ = output_type; // PS1 only
    let cats = load_categories();
    let ids: HashSet<String> = action_ids.into_iter().collect();
    let mut scripts = Vec::new();
    for cat in &cats {
        collect_scripts(cat, &ids, &mut scripts);
    }
    let body = if scripts.is_empty() {
        String::from("# No actions selected.\n")
    } else {
        scripts.join("\n")
    };
    Ok(format!("{}{}{}", SCRIPT_HEADER, body, SCRIPT_FOOTER))
}

#[tauri::command]
pub async fn run_built_script(app: tauri::AppHandle, code: String, script_type: String) -> Result<RunResult, String> {
    let tmp = std::env::temp_dir().join(format!("ctrl_built.{}", script_type));
    std::fs::write(&tmp, &code).map_err(|e| e.to_string())?;
    let path = tmp.to_string_lossy().to_string();
    let (program, args): (&str, Vec<String>) = match script_type.as_str() {
        "ps1" => (ps_bin(), vec!["-ExecutionPolicy".into(), "Bypass".into(), "-File".into(), path]),
        _     => ("cmd", vec!["/c".into(), path]),
    };
    let out = app.shell().command(program).args(&args).output().await.map_err(|e| e.to_string())?;
    let output = String::from_utf8_lossy(&out.stdout).to_string()
              + &String::from_utf8_lossy(&out.stderr);
    Ok(RunResult { success: out.status.success(), output })
}

#[tauri::command]
pub fn save_built_script(state: State<AppState>, code: String, name: String, script_type: String) -> Result<(), String> {
    let db = state.0.lock().map_err(|e| e.to_string())?;
    db.execute(
        "INSERT INTO scripts (name,description,category,file_path,script_type,tags,status,run_as_admin,content) \
         VALUES (?1,'Built with Script Builder','Builder','',?2,'','active',0,?3)",
        params![name, script_type, code],
    ).map_err(|e| e.to_string())?;
    Ok(())
}
